/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Classes.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JRException;
import Classes.Formularios;

/**
 *
 * @author julya
 */
public class MenuPrincipal extends javax.swing.JFrame {
    Connection con = null;
    Conexao conexao=new Conexao();
    String Usuario;
    
    Formularios form = new Formularios();

    
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(String User) {
        this.Usuario=User;
        initComponents();
       conexao.Conectar();
        
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSolicitacao = new javax.swing.JMenu();
        jMenuItemPedidoColeta = new javax.swing.JMenuItem();
        jMenuItemConsultaSolicitacao = new javax.swing.JMenuItem();
        jMenuFeedback = new javax.swing.JMenu();
        jMenuItemNovoFeedback = new javax.swing.JMenuItem();
        jMenuItemConsultaFeedback = new javax.swing.JMenuItem();
        jMenuEstatisticas = new javax.swing.JMenu();
        jMenuItemAnalisarDados = new javax.swing.JMenuItem();
        jMenuRelatórios = new javax.swing.JMenu();
        jMenuItemListaCli = new javax.swing.JMenuItem();
        jMenuItemListaSol = new javax.swing.JMenuItem();
        jMenuEditarCadastro = new javax.swing.JMenu();
        jMenuItemEditarCadastro = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuItemVersao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PRINCIPAL");
        setAutoRequestFocus(false);

        jDesktopPane1.setBackground(new java.awt.Color(204, 255, 204));
        jDesktopPane1.setForeground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1584, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setAlignmentX(jMenuBar1.getAlignmentX());
        jMenuBar1.setAlignmentY(jMenuBar1.getAlignmentY());
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setMargin(new java.awt.Insets(1, 2, 1, 2));

        jMenuSolicitacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuSolicitacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/recycle-triangular.png"))); // NOI18N
        jMenuSolicitacao.setText("SOLICITAÇÕES");
        jMenuSolicitacao.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jMenuSolicitacao.setMargin(new java.awt.Insets(1, 2, 1, 2));

        jMenuItemPedidoColeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/truck.png"))); // NOI18N
        jMenuItemPedidoColeta.setText("PEDIDOS DE COLETAS");
        jMenuItemPedidoColeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPedidoColetaActionPerformed(evt);
            }
        });
        jMenuSolicitacao.add(jMenuItemPedidoColeta);

        jMenuItemConsultaSolicitacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/calendar-check.png"))); // NOI18N
        jMenuItemConsultaSolicitacao.setText("CONSULTA SOLICITAÇÕES");
        jMenuItemConsultaSolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaSolicitacaoActionPerformed(evt);
            }
        });
        jMenuSolicitacao.add(jMenuItemConsultaSolicitacao);

        jMenuBar1.add(jMenuSolicitacao);

        jMenuFeedback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuFeedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/management.png"))); // NOI18N
        jMenuFeedback.setText("FEEDBACK");
        jMenuFeedback.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N

        jMenuItemNovoFeedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/Feedback.png"))); // NOI18N
        jMenuItemNovoFeedback.setText("NOVO FEEDBACK");
        jMenuItemNovoFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovoFeedbackActionPerformed(evt);
            }
        });
        jMenuFeedback.add(jMenuItemNovoFeedback);

        jMenuItemConsultaFeedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/FeedbackConsulta.png"))); // NOI18N
        jMenuItemConsultaFeedback.setText("CONSULTA FEEDBACK");
        jMenuItemConsultaFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaFeedbackActionPerformed(evt);
            }
        });
        jMenuFeedback.add(jMenuItemConsultaFeedback);

        jMenuBar1.add(jMenuFeedback);

        jMenuEstatisticas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuEstatisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/line-chart.png"))); // NOI18N
        jMenuEstatisticas.setText("ESTATISTICAS");
        jMenuEstatisticas.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N

        jMenuItemAnalisarDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/AnalisarEstatistica.png"))); // NOI18N
        jMenuItemAnalisarDados.setText("ANALISAR DADOS");
        jMenuItemAnalisarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnalisarDadosActionPerformed(evt);
            }
        });
        jMenuEstatisticas.add(jMenuItemAnalisarDados);

        jMenuBar1.add(jMenuEstatisticas);

        jMenuRelatórios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuRelatórios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/Relatorio.png"))); // NOI18N
        jMenuRelatórios.setText("RELATÓRIOS");
        jMenuRelatórios.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jMenuRelatórios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatóriosActionPerformed(evt);
            }
        });

        jMenuItemListaCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/RelatCliente.png"))); // NOI18N
        jMenuItemListaCli.setText("Listagem de Clientes");
        jMenuItemListaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaCliActionPerformed(evt);
            }
        });
        jMenuRelatórios.add(jMenuItemListaCli);

        jMenuItemListaSol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/SolicitaRelat.png"))); // NOI18N
        jMenuItemListaSol.setText("Lista Solicitações");
        jMenuItemListaSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaSolActionPerformed(evt);
            }
        });
        jMenuRelatórios.add(jMenuItemListaSol);

        jMenuBar1.add(jMenuRelatórios);

        jMenuEditarCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuEditarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/contract.png"))); // NOI18N
        jMenuEditarCadastro.setText("EDITAR CADASTRO");
        jMenuEditarCadastro.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N

        jMenuItemEditarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/Cadastro.png"))); // NOI18N
        jMenuItemEditarCadastro.setText("EDITAR MEU CADASTRO");
        jMenuItemEditarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarCadastroActionPerformed(evt);
            }
        });
        jMenuEditarCadastro.add(jMenuItemEditarCadastro);

        jMenuBar1.add(jMenuEditarCadastro);

        jMenuSobre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/computing.png"))); // NOI18N
        jMenuSobre.setText("SOBRE O SOFTWARE");
        jMenuSobre.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSobreActionPerformed(evt);
            }
        });

        jMenuItemVersao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/software.png"))); // NOI18N
        jMenuItemVersao.setText("    VERSAO");
        jMenuItemVersao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVersaoActionPerformed(evt);
            }
        });
        jMenuSobre.add(jMenuItemVersao);

        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1))
        );

        getAccessibleContext().setAccessibleParent(this);

        setSize(new java.awt.Dimension(1600, 770));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNovoFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovoFeedbackActionPerformed
        TelaFeedback telaFeed;
        form.abrirform(telaFeed = new TelaFeedback(), jDesktopPane1);
      
    }//GEN-LAST:event_jMenuItemNovoFeedbackActionPerformed

    private void jMenuItemConsultaSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaSolicitacaoActionPerformed
    TelaConsultaSolicitacoes telacon;
    form.abrirform(telacon = new TelaConsultaSolicitacoes(), jDesktopPane1);

    }//GEN-LAST:event_jMenuItemConsultaSolicitacaoActionPerformed

    private void jMenuItemConsultaFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaFeedbackActionPerformed
    TelaConsultaFeedback telafeed;
    form.abrirform(telafeed = new TelaConsultaFeedback(), jDesktopPane1);

    }//GEN-LAST:event_jMenuItemConsultaFeedbackActionPerformed

    private void jMenuItemEditarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarCadastroActionPerformed
        TelaEditarCadastro telaCad;
        form.abrirform(telaCad = new TelaEditarCadastro(this.Usuario), jDesktopPane1);
    }//GEN-LAST:event_jMenuItemEditarCadastroActionPerformed

    private void jMenuItemAnalisarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnalisarDadosActionPerformed
    TelaEstatisticas telaEst;
    form.abrirform(telaEst = new TelaEstatisticas(), jDesktopPane1);
    }//GEN-LAST:event_jMenuItemAnalisarDadosActionPerformed

    private void jMenuItemPedidoColetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPedidoColetaActionPerformed

        TelaPedido telaped;
        form.abrirform(telaped = new TelaPedido(), jDesktopPane1);
    }//GEN-LAST:event_jMenuItemPedidoColetaActionPerformed


    private void jMenuItemListaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaCliActionPerformed
                                                    
        try {
        ResultSet RStemp=conexao.buscaRelatorio("Select * from dadosusuarios"); 
        RStemp.first();
            JRResultSetDataSource relatResul = new JRResultSetDataSource(RStemp);
            JasperPrint jpPrint = JasperFillManager.fillReport("C:\\Users\\julya\\OneDrive\\Documentos\\NetBeansProjects\\ColetaSeletiva\\reports\\LISTACLIENTES.jasper",new HashMap(), relatResul);
            JasperViewer jv = new JasperViewer(jpPrint,false);
            jv.setVisible(true);
            } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao chamar o relatorio!\nErro:"+e);
        }
    }//GEN-LAST:event_jMenuItemListaCliActionPerformed

    private void jMenuItemListaSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaSolActionPerformed
        try {
        ResultSet RStemp=conexao.buscaRelatorio("Select * from coleta_tb_solicitacao"); 
        RStemp.first();
            JRResultSetDataSource relatResul = new JRResultSetDataSource(RStemp);
            JasperPrint jpPrint = JasperFillManager.fillReport("C:/Users/julya/OneDrive/Documentos/NetBeansProjects/ColetaSeletiva/reports/Consultas.jasper",new HashMap(), relatResul);
            JasperViewer jv = new JasperViewer(jpPrint,false);
            jv.setVisible(true);
            } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao chamar o relatorio!\nErro:"+e);
        }
            
    }//GEN-LAST:event_jMenuItemListaSolActionPerformed

    private void jMenuRelatóriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatóriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuRelatóriosActionPerformed

    private void jMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSobreActionPerformed
             
    }//GEN-LAST:event_jMenuSobreActionPerformed

    private void jMenuItemVersaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVersaoActionPerformed
         TelaSobre telasoft;
             form.abrirform(telasoft = new TelaSobre(), jDesktopPane1);
    }//GEN-LAST:event_jMenuItemVersaoActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     /*   try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEditarCadastro;
    private javax.swing.JMenu jMenuEstatisticas;
    private javax.swing.JMenu jMenuFeedback;
    private javax.swing.JMenuItem jMenuItemAnalisarDados;
    private javax.swing.JMenuItem jMenuItemConsultaFeedback;
    private javax.swing.JMenuItem jMenuItemConsultaSolicitacao;
    private javax.swing.JMenuItem jMenuItemEditarCadastro;
    private javax.swing.JMenuItem jMenuItemListaCli;
    private javax.swing.JMenuItem jMenuItemListaSol;
    private javax.swing.JMenuItem jMenuItemNovoFeedback;
    private javax.swing.JMenuItem jMenuItemPedidoColeta;
    private javax.swing.JMenuItem jMenuItemVersao;
    private javax.swing.JMenu jMenuRelatórios;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JMenu jMenuSolicitacao;
    // End of variables declaration//GEN-END:variables

   
}
