/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JInternalFrame;

/**
 *
 * @author julya
 */
public class TelaSolicitacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaPedido
     */
    public TelaSolicitacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLDescricao = new javax.swing.JLabel();
        jLTipoResiduo = new javax.swing.JLabel();
        jLQuantidade = new javax.swing.JLabel();
        jFColeta_data = new javax.swing.JFormattedTextField();
        jLIdusuario = new javax.swing.JLabel();
        jLDataColeta = new javax.swing.JLabel();
        jLNomeusuario = new javax.swing.JLabel();
        jLEndereco = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTsolicitacao_descricao = new javax.swing.JTextArea();
        jTusuario_nome = new javax.swing.JTextField();
        jTenderecousuario = new javax.swing.JTextField();
        jBConfirmaColeta = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jFsolicitacao_data = new javax.swing.JFormattedTextField();
        jLDataSolicitacao = new javax.swing.JLabel();
        jTIdsolicitacao = new javax.swing.JTextField();
        jLIdsolicitacao = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("NOVA SOLICITAÇÂO");
        getContentPane().setLayout(null);

        jLDescricao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLDescricao.setForeground(new java.awt.Color(51, 51, 51));
        jLDescricao.setText("DESCRIÇÃO DA SOLICITAÇÃO ");
        getContentPane().add(jLDescricao);
        jLDescricao.setBounds(10, 253, 286, 17);

        jLTipoResiduo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLTipoResiduo.setForeground(new java.awt.Color(51, 51, 51));
        jLTipoResiduo.setText("TIPO DE RESÍDUO");
        getContentPane().add(jLTipoResiduo);
        jLTipoResiduo.setBounds(409, 253, 122, 17);

        jLQuantidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLQuantidade.setForeground(new java.awt.Color(51, 51, 51));
        jLQuantidade.setText("QUANTIDADE/VOLUME À SER RECOLHIDO");
        getContentPane().add(jLQuantidade);
        jLQuantidade.setBounds(10, 444, 286, 17);

        jFColeta_data.setForeground(new java.awt.Color(102, 51, 0));
        try {
            jFColeta_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFColeta_data.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFColeta_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFColeta_dataActionPerformed(evt);
            }
        });
        getContentPane().add(jFColeta_data);
        jFColeta_data.setBounds(215, 200, 84, 20);

        jLIdusuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLIdusuario.setForeground(new java.awt.Color(51, 51, 51));
        jLIdusuario.setText("ID DO USUÁRIO");
        getContentPane().add(jLIdusuario);
        jLIdusuario.setBounds(534, 100, 106, 17);

        jLDataColeta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLDataColeta.setForeground(new java.awt.Color(51, 51, 51));
        jLDataColeta.setText("DATA DA COLETA");
        getContentPane().add(jLDataColeta);
        jLDataColeta.setBounds(10, 201, 195, 17);

        jLNomeusuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLNomeusuario.setForeground(new java.awt.Color(51, 51, 51));
        jLNomeusuario.setText("NOME DO USUÁRIO");
        getContentPane().add(jLNomeusuario);
        jLNomeusuario.setBounds(10, 100, 195, 17);

        jLEndereco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLEndereco.setForeground(new java.awt.Color(51, 51, 51));
        jLEndereco.setText("ENDEREÇO DE COLETA");
        getContentPane().add(jLEndereco);
        jLEndereco.setBounds(10, 146, 195, 17);

        jTsolicitacao_descricao.setColumns(20);
        jTsolicitacao_descricao.setRows(5);
        jScrollPane1.setViewportView(jTsolicitacao_descricao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 294, 449, 96);

        jTusuario_nome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jTusuario_nome);
        jTusuario_nome.setBounds(215, 99, 301, 20);

        jTenderecousuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jTenderecousuario);
        jTenderecousuario.setBounds(215, 145, 557, 20);

        jBConfirmaColeta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBConfirmaColeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/approve-invoice.png"))); // NOI18N
        jBConfirmaColeta.setText("COFIRMA COLETA");
        getContentPane().add(jBConfirmaColeta);
        jBConfirmaColeta.setBounds(490, 539, 220, 44);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(537, 248, 153, 28);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(314, 435, 145, 36);

        jFsolicitacao_data.setForeground(new java.awt.Color(102, 51, 0));
        try {
            jFsolicitacao_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFsolicitacao_data.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFsolicitacao_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFsolicitacao_dataActionPerformed(evt);
            }
        });
        getContentPane().add(jFsolicitacao_data);
        jFsolicitacao_data.setBounds(582, 20, 116, 20);

        jLDataSolicitacao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLDataSolicitacao.setForeground(new java.awt.Color(51, 51, 51));
        jLDataSolicitacao.setText("DATA DA SOLICITACAO");
        getContentPane().add(jLDataSolicitacao);
        jLDataSolicitacao.setBounds(410, 21, 162, 17);

        jTIdsolicitacao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTIdsolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIdsolicitacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jTIdsolicitacao);
        jTIdsolicitacao.setBounds(215, 23, 90, 20);

        jLIdsolicitacao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLIdsolicitacao.setForeground(new java.awt.Color(51, 51, 51));
        jLIdsolicitacao.setText("ID DA SOLICITAÇÃO");
        getContentPane().add(jLIdsolicitacao);
        jLIdsolicitacao.setBounds(10, 24, 195, 17);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(658, 99, 114, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFColeta_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFColeta_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFColeta_dataActionPerformed

    private void jFsolicitacao_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFsolicitacao_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFsolicitacao_dataActionPerformed

    private void jTIdsolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIdsolicitacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIdsolicitacaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirmaColeta;
    private javax.swing.JFormattedTextField jFColeta_data;
    private javax.swing.JFormattedTextField jFsolicitacao_data;
    private javax.swing.JLabel jLDataColeta;
    private javax.swing.JLabel jLDataSolicitacao;
    private javax.swing.JLabel jLDescricao;
    private javax.swing.JLabel jLEndereco;
    private javax.swing.JLabel jLIdsolicitacao;
    private javax.swing.JLabel jLIdusuario;
    private javax.swing.JLabel jLNomeusuario;
    private javax.swing.JLabel jLQuantidade;
    private javax.swing.JLabel jLTipoResiduo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTIdsolicitacao;
    private javax.swing.JTextField jTenderecousuario;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextArea jTsolicitacao_descricao;
    private javax.swing.JTextField jTusuario_nome;
    // End of variables declaration//GEN-END:variables
}
