/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Classes.Conexao;
import Classes.Solicitacao;
import java.awt.Dimension;
import java.util.ArrayList;
import Classes.EnvioEmail;
import javax.mail.internet.AddressException;
import Classes.Formularios;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author julya
 */
public class TelaPedido extends javax.swing.JInternalFrame {
Formularios form = new Formularios();


    public TelaPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBCarregaSolicitacao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSolicitacao = new javax.swing.JTable();
        jBVisualizaPedido = new javax.swing.JButton();
        jBFinalizaPedido = new javax.swing.JButton();
        jBAlteraStatus = new javax.swing.JButton();

        setClosable(true);

        jBCarregaSolicitacao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBCarregaSolicitacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/carregartabela.png"))); // NOI18N
        jBCarregaSolicitacao.setText("CARREGAR SOLICITAÇÃO");
        jBCarregaSolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCarregaSolicitacaoActionPerformed(evt);
            }
        });

        jTableSolicitacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID USUARIO", "ID SOLICITACAO", "DATA SOLICITACAO", "TIPO RESIDUO", "DESCRICAO", "QUANTIDADE", "RASTREAMENTO"
            }
        ));
        jScrollPane1.setViewportView(jTableSolicitacao);

        jBVisualizaPedido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBVisualizaPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/visualizarpedido.png"))); // NOI18N
        jBVisualizaPedido.setText("VISUALIZAR PEDIDO");
        jBVisualizaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVisualizaPedidoActionPerformed(evt);
            }
        });

        jBFinalizaPedido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBFinalizaPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/finalizapedido.png"))); // NOI18N
        jBFinalizaPedido.setText("FINALIZAR PEDIDO");
        jBFinalizaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizaPedidoActionPerformed(evt);
            }
        });

        jBAlteraStatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBAlteraStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/alterastatus.png"))); // NOI18N
        jBAlteraStatus.setText("ALTERA STATUS");
        jBAlteraStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlteraStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBCarregaSolicitacao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jBVisualizaPedido)
                .addGap(117, 117, 117)
                .addComponent(jBAlteraStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(jBFinalizaPedido)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBCarregaSolicitacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVisualizaPedido)
                    .addComponent(jBFinalizaPedido)
                    .addComponent(jBAlteraStatus))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1009, 540);
    }// </editor-fold>//GEN-END:initComponents

    
    public void setPosicao() {
        
     Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 4, (d.height - this.getSize().height) / 4); }
    
    
    
    
    private void jBCarregaSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCarregaSolicitacaoActionPerformed
        
        String sql="select * from coleta_tb_solicitacao where solicitacao_rastreamento='Aberto' or solicitacao_rastreamento='Aguardando'";
        Conexao conexao=new Conexao();
        conexao.Conectar();
        ArrayList<Solicitacao> l = new ArrayList<>();
        l=conexao.busca(sql);
        for(int i = 0; i< jTableSolicitacao.getRowCount(); i++){
            jTableSolicitacao.setValueAt("", i, 0);
            jTableSolicitacao.setValueAt("", i, 1);
            jTableSolicitacao.setValueAt("", i, 2);
            jTableSolicitacao.setValueAt("", i, 3);
            jTableSolicitacao.setValueAt("", i, 4);
            jTableSolicitacao.setValueAt("", i, 5);
            jTableSolicitacao.setValueAt("", i, 6);
            
            
        }
        for(int i = 0; i< l.size(); i++){
            Solicitacao sol=new Solicitacao();
            sol=l.get(i);
            jTableSolicitacao.setValueAt(sol.getUsuario(), i, 0);
            jTableSolicitacao.setValueAt(sol.getId(), i, 1);
            jTableSolicitacao.setValueAt(sol.getData(), i, 2);
            jTableSolicitacao.setValueAt(sol.getTiporesiduo(), i, 3);
            jTableSolicitacao.setValueAt(sol.getDescricao(), i, 4);
            jTableSolicitacao.setValueAt(sol.getQuantidade(), i, 5);
            jTableSolicitacao.setValueAt(sol.getRastreamento(), i, 6);
            
            
        }
        
        conexao.Desconecta();
        
        
    }//GEN-LAST:event_jBCarregaSolicitacaoActionPerformed

    private void jBVisualizaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVisualizaPedidoActionPerformed
String text=String.valueOf(jTableSolicitacao.getValueAt(jTableSolicitacao.getSelectedRow(), jTableSolicitacao.getSelectedColumn()));
TelaPedidoIndividual tela = new TelaPedidoIndividual(text);
getParent().add(tela);
tela.setVisible(true);
tela.toFront();
tela.setPosicao();
    }//GEN-LAST:event_jBVisualizaPedidoActionPerformed

    private void jBAlteraStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlteraStatusActionPerformed

String text=String.valueOf(jTableSolicitacao.getValueAt(jTableSolicitacao.getSelectedRow(), jTableSolicitacao.getSelectedColumn()));
TelaEnvioEmail telaemail = new TelaEnvioEmail(text);
getParent().add(telaemail);
telaemail.setVisible(true);
telaemail.toFront();
telaemail.setPosicao();



    }//GEN-LAST:event_jBAlteraStatusActionPerformed

    private void jBFinalizaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizaPedidoActionPerformed
        // TODO add your handling code here:
        String text=String.valueOf(jTableSolicitacao.getValueAt(jTableSolicitacao.getSelectedRow(), jTableSolicitacao.getSelectedColumn()));
        String sql = "update coleta_tb_solicitacao set solicitacao_rastreamento='Finalizado' where  solicitacao_id="+text;
        
        
        Conexao conexao=new Conexao();
        conexao.Conectar();
        conexao.comando(sql);
        conexao.Desconecta();
        
       
        
    }//GEN-LAST:event_jBFinalizaPedidoActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlteraStatus;
    private javax.swing.JButton jBCarregaSolicitacao;
    private javax.swing.JButton jBFinalizaPedido;
    private javax.swing.JButton jBVisualizaPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSolicitacao;
    // End of variables declaration//GEN-END:variables
}
